add_newline = false
# A minimal left prompt
format = """$directory$character"""
palette = "catppuccin_mocha"
# move the rest of the prompt to the right
right_format = """$all"""
command_timeout = 1000

# [character]
# vicmd_symbol = "[N] >>>"
# success_symbol = '[➜](bold green)'

[custom.container]
command = """
if [ -f /.dockerenv ]; then
  echo "🐳 $(hostname)"
elif [ -n "$DISTROBOX_NAME" ]; then
  echo "📦 $DISTROBOX_NAME"
fi
"""
when = "test -f /.dockerenv || test -n \"$DISTROBOX_NAME\""
format = "[$output]($style) "
style = "blue"


[git_branch]
format =  '[$symbol$branch(:$remote_branch)]($style)'
style = 'sky'

[git_status]
style = 'sky'
format = '([\[$all_status$ahead_behind\]]($style)) '
# disabled = false

[palettes.catppuccin_mocha]
rosewater = "#f5e0dc"
flamingo = "#f2cdcd"
pink = "#f5c2e7"
mauve = "#cba6f7"
red = "#f38ba8"
maroon = "#eba0ac"
peach = "#fab387"
yellow = "#f9e2af"
green = "#a6e3a1"
teal = "#94e2d5"
sky = "#89dceb"
sapphire = "#74c7ec"
blue = "#89b4fa"
lavender = "#b4befe"
text = "#cdd6f4"
subtext1 = "#bac2de"
subtext0 = "#a6adc8"
overlay2 = "#9399b2"
overlay1 = "#7f849c"
overlay0 = "#6c7086"
surface2 = "#585b70"
surface1 = "#45475a"
surface0 = "#313244"
base = "#1e1e2e"
mantle = "#181825"

[cmake]
disabled = true

[c]
disabled = true

[cpp]
disabled = true

[python]
format = '[$virtualenv]($style) '

[ruby]
disabled = true

[golang]
disabled = true

[rust]
disabled = true

[php]
disabled = true

[java]
disabled = true

[dotnet]
disabled = true

[swift]
disabled = true

[scala]
disabled = true

[perl]
disabled = true

[elm]
disabled = true

[erlang]
disabled = true

[ocaml]
disabled = true

[gradle]
disabled = true

[deno]
disabled = true


